# Site settings
title: 卡卡恩解題
email: math.tmt514+probsolve@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  這個世界上有太多太有趣的題目和太厲害的程式碼了！
  這邊將會記錄各種大大小小程式/數學解題的各種心得。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tmt514.github.io" # the base hostname & protocol for your site
twitter_username: tmt514
github_username:  tmt514

# Build settings
markdown: kramdown
